name: Setup kind
description: Deploy kind cluster

inputs:
  kind-version:
    description: Kind version
    required: true

runs:
  using: composite
  steps:
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.5.0
      with:
        # https://github.com/helm/kind-action?tab=readme-ov-file#inputs
        node_image: "kindest/node:${{ inputs.kind-version }}"
        verbosity: 10
        cluster_name: "build-cluster-${{ github.job }}"
        kubectl_version: "${{ inputs.kind-version }}"
        ignore_failed_clean: true # Ignore the post delete cluster action failing
        wait: "180s" # Max timeout to wait Kind becomes ready


